// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgpcztK-tOAfx4MTuHywpV2ZfVQlA55y8',
    appId: '1:81423788056:web:71522cb7c89bb89989fb6d',
    messagingSenderId: '81423788056',
    projectId: 'calo-booking-app',
    authDomain: 'calo-booking-app.firebaseapp.com',
    storageBucket: 'calo-booking-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5kDKjHSzPJBKG-LEKc-S1g2POyO-W-pY',
    appId: '1:81423788056:android:72e59bd52f33db1989fb6d',
    messagingSenderId: '81423788056',
    projectId: 'calo-booking-app',
    storageBucket: 'calo-booking-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqbqQkEAMQISIdCLkBLWO9BV86vLUOYbY',
    appId: '1:81423788056:ios:3fa138bc8fe9c5e189fb6d',
    messagingSenderId: '81423788056',
    projectId: 'calo-booking-app',
    storageBucket: 'calo-booking-app.firebasestorage.app',
    iosBundleId: 'com.example.caloBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqbqQkEAMQISIdCLkBLWO9BV86vLUOYbY',
    appId: '1:81423788056:ios:3fa138bc8fe9c5e189fb6d',
    messagingSenderId: '81423788056',
    projectId: 'calo-booking-app',
    storageBucket: 'calo-booking-app.firebasestorage.app',
    iosBundleId: 'com.example.caloBookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgpcztK-tOAfx4MTuHywpV2ZfVQlA55y8',
    appId: '1:81423788056:web:7280995a4edb914689fb6d',
    messagingSenderId: '81423788056',
    projectId: 'calo-booking-app',
    authDomain: 'calo-booking-app.firebaseapp.com',
    storageBucket: 'calo-booking-app.firebasestorage.app',
  );
}
